### ISSUE TITLE
Enabling button builder breaks TinyMCE visual editor

### ISSUE THREAD

**Issue by ZachTRice** [hps/heartland-wordpress-plugin#37]
On a fresh install WordPress enabling the button builder option breaks the editor. Initially, I thought this could be due to the TinyMCE update in WP 4.5 but this issue also occurs on a fresh install of WP 4.4.2.

**Comment by ZachTRice** [comment]
The problem was that I downloaded the plugin via github, not through the wordpress directory, therefore the folder name was heartland-wordpress-plugin-master. Since the paths in your plugin are hardcoded to **securesubmit**/.../.../, when I uploaded the ZIP or extracted to the plugins folder directly, this broke the functionality. 

I recommended rewriting this portion of the plugin because I was sent the link to Heartland to grab this plugin and implement so my process went as such: Link to Heartland -> logged in -> clicked Cart & Platform Support -> Clicked WordPress -> Clicked download which directed me to the GitHub page to download; uploaded ZIP, ran into issue. I think a lot of other users might run into this same issue.

**Comment by ZachTRice** [comment]
You might want to try   
`$plugin_array['securesubmit']  =  plugins_url('js/securesubmit_plugin.js', __FILE__ );`

Instead of: 
`$plugin_array['securesubmit']  =  plugins_url('/securesubmit/js/securesubmit_plugin.js');`

Or look into using:   
https://developer.wordpress.org/reference/functions/plugin_dir_path

**Comment by ttnnkkrr** [comment]
Thank you for this feedback Zack. We will review this for our next update
